name: CI - Complete
on:
  pull_request:
    branches:
      - main
jobs:
  full-quality-testing:
    name: Complete Quality Control (Unit, Integration & System Tests)
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: goeventsnow_db
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=5
        
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          
      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
          
      - name: Install Dependencies
        run: | 
          cd frontend
          npm install

          
      - name: Compile Server & Run Backend Unit & Integration Test 
        run: |
          cd backend
          mvn clean verify -Dtest="es.goeventsnow.backend.unit.EventTest,es.goeventsnow.backend.integration.EventBBDDTest"

      - name: Run Frontend Unit & Integration tests
        run: |
          cd frontend
          npx ng test --coverage 

      - name: Install wait tools
        run: sudo apt-get install netcat-openbsd

      - name: Run Backend
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/goeventsnow_db?useSSL=false&serverTimezone=UTC
          SPRING_DATASOURCE_PASSWORD: password
        run: |
          cd backend
          mvn spring-boot:run &
          echo "Waiting backend to be in port 8080..."
          timeout 120s sh -c 'until nc -z localhost 8080; do sleep 5; done'

      - name: Run Frontend
        run: |
          cd frontend
          npx ng serve --host 0.0.0.0 &
          echo "Waiting frontend to be in port 4200..."
          timeout 120s sh -c 'until nc -z localhost 4200; do sleep 5; done'

      - name: Run Backend & Frontend System Tests
        run: |
          cd backend
          mvn test -Dtest="es.goeventsnow.backend.e2e.SeleniumTest,es.goeventsnow.backend.api.EventApiTest"
